import type { Metadata } from 'next';
import { stageGroteskBlack, stageGroteskMedium } from '@/fonts';
import './globals.css';
import { GSAP } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${stageGroteskBlack.variable} ${stageGroteskMedium.variable}`}>
        {children}
        <GSAP />
      </body>
    </html>
  );
}
